# Theme settings
doks:
    baseurl: /gisportal
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: GIS PORTAL
            image:
        nav:
            - item_name: Demo
              external_url: 'https://test.level2.si'
            - item_name: Code
              item_url: 'https://github.com/level2-gis/gisportal'
              external_url: true
    footer:
        content:
            logo:
                text: GIS PORTAL
                image:
            copyright: Copyright &copy; 2019. - Level2 <br>All rights reserved.
        social_list:
            - network_name: github
              profile_url: 'https://github.com/level2-gis/gisportal'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
